#!/bin/bash
# install-statusline.sh — lets Monkey show usage-limit %.
#
# Claude Code pipes rate-limit data only to statusline commands, never to hooks and
# never to disk, so there's no other way for Monkey to read it.
#
# This wraps your existing statusline script rather than editing it: your original
# script is renamed to statusline-command.monkey-original.sh, and a small new
# statusline-command.sh takes its place — it reads stdin itself, caches the numbers
# Monkey needs, then forwards that same input to your original script and prints
# whatever it prints. Your statusline's actual output is completely unchanged.
#
# Wrapping like this (instead of appending code into your script, which an earlier
# version of this did) is deliberate: appended code can only reuse stdin if your
# script happened to save it to a variable of a name we guessed correctly. That's
# true of the author's own statusline script, but not a safe assumption about
# anyone else's — a silent guess-wrong means Monkey's usage % just never appears,
# with nothing telling you why. Capturing stdin ourselves, before your script ever
# runs, works no matter how your script is written internally.
#
# Safe to run twice: it detects its own wrapper and does nothing the second time.

set -euo pipefail

SL="$HOME/.claude/statusline-command.sh"
ORIGINAL="$HOME/.claude/statusline-command.monkey-original.sh"
MARKER="# monkey-statusline-wrapper"

if [ ! -f "$SL" ]; then
  echo "No statusline script at $SL"
  echo "Set one up first (Claude Code: /statusline), then re-run this."
  exit 1
fi

if grep -qF "$MARKER" "$SL"; then
  echo "Already installed — nothing to do."
  exit 0
fi

# An earlier version of this script edited your statusline in place instead of
# wrapping it, leaving a "# --- monkey: cache rate limits ---" block appended
# directly to the end of it and a pristine copy at .monkey-backup. Migrate
# cleanly off that: restore the pristine backup before wrapping, so the old
# appended block doesn't end up duplicated inside the new wrapper's "original".
OLD_MARKER="# --- monkey: cache rate limits ---"
if grep -qF "$OLD_MARKER" "$SL" && [ -f "$SL.monkey-backup" ]; then
  echo "Migrating from the older in-place-edit version..."
  cp "$SL.monkey-backup" "$SL"
fi

mv "$SL" "$ORIGINAL"
chmod +x "$ORIGINAL"
echo "Moved your statusline to: $ORIGINAL"

cat > "$SL" <<EOF
#!/bin/bash
$MARKER — generated by install-statusline.sh. Your real statusline moved to
# $ORIGINAL and is called at the bottom of this file, unmodified.
# To uninstall: rm this file, then mv "$ORIGINAL" "$SL".

input="\$(cat)"

# Cache rate-limit percentages where Monkey can read them. Best-effort: any
# failure here (missing jq, malformed input) must never block your real
# statusline from running.
{
  mkdir -p "\$HOME/.claude/monkey"
  printf '{"five_hour":%s,"seven_day":%s}\n' \\
    "\$(printf '%s' "\$input" | jq -r '.rate_limits.five_hour.used_percentage // "null"' 2>/dev/null)" \\
    "\$(printf '%s' "\$input" | jq -r '.rate_limits.seven_day.used_percentage // "null"' 2>/dev/null)" \\
    > "\$HOME/.claude/monkey/limits.json.tmp" 2>/dev/null && \\
    mv -f "\$HOME/.claude/monkey/limits.json.tmp" "\$HOME/.claude/monkey/limits.json" 2>/dev/null
} 2>/dev/null || true

printf '%s' "\$input" | "$ORIGINAL"
EOF

chmod +x "$SL"

echo "Installed. Monkey will pick up usage % on the next statusline refresh."
